services:
  pebble:
    container_name: "go-acme-pebble"
    image: "ghcr.io/letsencrypt/pebble:latest"
    command: >
      -config test/config/pebble-config.json
      -strict
    environment:
      PEBBLE_WFE_NONCEREJECT: "50"
      PEBBLE_VA_NOSLEEP: "1"
    network_mode: "host"
